[workspace]
resolver = "3"
members = ["yt-sub"]

[workspace.dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
winnow = "0.7"
