[package]
name = "summarize"
version = "0.1.0"
edition = "2024"

[dependencies]
anthropic_api = { path = "../anthropic_api" }
anyhow = { workspace = true }
clap = { workspace = true }
clap-stdin = "0.8.0"
tokio = { workspace = true }
